
services:
  redis:
    image: redis:latest
    container_name: space-guess-redis
    ports:
      - "6380:6379"
    restart: always

  backend:
    build: ./backend
    container_name: space-guess-backend
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    restart: always

  frontend:
    build: ./frontend
    container_name: space-guess-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
